import {
  ArchiveX,
  ArrowLeft,
  ArrowRight,
  ArrowRightCircle,
  Bell,
  BellRing,
  Book,
  Calendar,
  Car,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  CircleCheckBig,
  CirclePause,
  CircleX,
  CirclePlay,
  ClipboardPen,
  ClipboardPenLine,
  Clock10,
  Cog,
  Crop,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  View,
  File,
  FileInput,
  FileOutput,
  FilePen,
  FilePlus,
  FileText,
  Forward,
  Glasses,
  HandHelping,
  History,
  Image,
  Inbox,
  Info,
  Link2,
  Link2Off,
  ListChecks,
  ListFilter,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Monitor,
  Moon,
  Palette,
  Paperclip,
  Pen,
  Pencil,
  PencilLine,
  PersonStanding,
  Plus,
  PlusCircle,
  Receipt,
  Redo,
  RefreshCcw,
  SendHorizontal,
  Split,
  SquarePen,
  Sun,
  TextSelect,
  Text,
  ThumbsDown,
  Trash,
  Trash2,
  Undo2,
  Upload,
  User,
  UserCog,
  Users,
  Wallet,
  X,
  type LucideProps,
} from 'lucide-react';

const iconMap: Record<string, React.FC<LucideProps>> = {
  'archive-x': ArchiveX,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-right-circle': ArrowRightCircle,
  bell: Bell,
  'bell-ring': BellRing,
  book: Book,
  calendar: Calendar,
  car: Car,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'circle-alert': CircleAlert,
  'circle-check-big': CircleCheckBig,
  'circle-pause': CirclePause,
  'circle-x': CircleX,
  'circle-play': CirclePlay,
  'clipboard-pen': ClipboardPen,
  'clipboard-pen-line': ClipboardPenLine,
  'clock-10': Clock10,
  cog: Cog,
  crop: Crop,
  download: Download,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  eye: Eye,
  view: View,
  file: File,
  'file-input': FileInput,
  'file-output': FileOutput,
  'file-pen': FilePen,
  'file-plus': FilePlus,
  'file-text': FileText,
  forward: Forward,
  glasses: Glasses,
  'helping-hand': HandHelping,
  history: History,
  image: Image,
  inbox: Inbox,
  info: Info,
  'link-2': Link2,
  'link-2-off': Link2Off,
  'list-checks': ListChecks,
  'list-filter': ListFilter,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  'message-circle': MessageCircle,
  monitor: Monitor,
  moon: Moon,
  palette: Palette,
  paperclip: Paperclip,
  pen: Pen,
  pencil: Pencil,
  'pencil-line': PencilLine,
  'person-standing': PersonStanding,
  plus: Plus,
  'plus-circle': PlusCircle,
  receipt: Receipt,
  redo: Redo,
  'refresh-ccw': RefreshCcw,
  'send-horizontal': SendHorizontal,
  split: Split,
  'square-pen': SquarePen,
  sun: Sun,
  'text-select': TextSelect,
  text: Text,
  'thumbs-down': ThumbsDown,
  trash: Trash,
  'trash-2': Trash2,
  'undo-2': Undo2,
  upload: Upload,
  user: User,
  'user-cog': UserCog,
  users: Users,
  wallet: Wallet,
  x: X,
};

export default iconMap;
