services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        DRAKEN_BUILD_DRAGON: ${DRAKEN_BUILD_DRAGON:?Select a dragon from dragons.json}
    ports:
      - "${BACKEND_PORT-3001}:3000"
    container_name: ${COMPOSE_PROJECT_NAME}-backend-${NODE_ENV}
    volumes:
      - data:/app/backend/data
    network_mode: bridge
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        DRAKEN_BUILD_DRAGON: ${DRAKEN_BUILD_DRAGON:?Select a dragon from dragons.json}
    ports:
      - "${FRONTEND_PORT-3000}:3000"
    container_name: ${COMPOSE_PROJECT_NAME}-frontend-${NODE_ENV}
    network_mode: bridge
volumes:
  data:
