export enum PTCaseLabel {
  PARKING_PERMIT = 'Nytt parkeringstillstånd',
  PARKING_PERMIT_RENEWAL = 'Förnyat parkeringstillstånd',
  LOST_PARKING_PERMIT = 'Borttappat parkeringstillstånd',
  APPEAL = 'Överklagan',
}

export enum FTCaseLabel {
  PARATRANSIT = 'Ansökan av färdtjänst',
  PARATRANSIT_RENEWAL = 'Ansökan om fortsatt färdtjänst',
  PARATRANSIT_CHANGE = 'Ansökan om förändring av insatser',
  PARATRANSIT_NATIONAL = 'Ansökan om riksfärdtjänst',
  PARATRANSIT_NATIONAL_RENEWAL = 'Ansökan om fortsatt riksfärdtjänst',
  PARATRANSIT_RIAK = 'Ansökan om RIAK',
  PARATRANSIT_BUS_CARD = 'Ansökan om busskort',
  PARATRANSIT_NOTIFICATION = 'Anmälan av färdtjänst',
  PARATRANSIT_NOTIFICATION_CHANGE = 'Anmälan om förändring av insatser',
  PARATRANSIT_NOTIFICATION_RENEWAL = 'Anmälan om fortsatt färdtjänst',
  PARATRANSIT_NOTIFICATION_NATIONAL = 'Anmälan om riksfärdtjänst',
  PARATRANSIT_NOTIFICATION_NATIONAL_RENEWAL = 'Anmälan om fortsatt riksfärdtjänst',
  PARATRANSIT_NOTIFICATION_RIAK = 'Anmälan om RIAK',
  PARATRANSIT_NOTIFICATION_BUS_CARD = 'Anmälan om busskort',
}

export enum MEXCaseLabel {
  'MEX_SQUARE_PLACE' = 'Torgplats',
  'MEX_REQUEST_FOR_PUBLIC_DOCUMENT' = 'Begäran om allmän handling',
  'MEX_INVOICE' = 'Faktura',
  'MEX_LEASE_REQUEST' = 'Arrende/Nyttjanderätt',
  'MEX_BUY_LAND_FROM_THE_MUNICIPALITY' = 'Köpa kommunal mark',
  'MEX_BUY_SMALL_HOUSE_PLOT' = 'Köpa småhustomt',
  'MEX_LAND_SURVEYING_OFFICE' = 'Lantmäteriförrättning',
  'MEX_LAND_INSTRUCTION' = 'Markanvisning',
  'MEX_UNAUTHORIZED_RESIDENCE' = 'Otillåten bosättning',
  'MEX_REFERRAL_BUILDING_PERMIT_EARLY_DIALOGUE_PLANNING_NOTICE' = 'Remiss/Bygglov/Tidig dialog planbesked',
  'MEX_PROTECTIVE_HUNTING' = 'Skyddsjakt',
  'MEX_SELL_LAND_TO_THE_MUNICIPALITY' = 'Kommunens inköp av mark',
  'MEX_EARLY_DIALOG_PLAN_NOTIFICATION' = 'Tidig dialog planbesked',
  'MEX_LAND_RIGHT' = 'Tomträtt',
  'MEX_TERMINATION_OF_LEASE' = 'Arrende/Nyttjanderätt, uppsägning',
  'MEX_HUNTING_LEASE' = 'Jakträtt',
  'MEX_APPLICATION_FOR_ROAD_ALLOWANCE' = 'Vägbidrag',
  'MEX_FORWARDED_FROM_CONTACTSUNDSVALL' = 'Ärende från Kontakt Sundsvall',
  'MEX_OTHER' = 'Övrigt',
  'MEX_BUILDING_PERMIT' = 'Bygglov ',
  'MEX_STORMWATER' = 'Dagvatten ',
  'MEX_INVASIVE_SPECIES' = 'Invasiva arter',
  'MEX_LAND_USE_AGREEMENT_VALUATION_PROTOCOL' = 'Markupplåtelseavtal /Värderingsprotokoll ',
  'MEX_LITTERING' = 'Nedskräpning',
  'MEX_REFERRAL_CONSULTATION' = 'Remiss/Samråd',
  'MEX_PUBLIC_SPACE_LEASE' = 'Upplåtelse av allmän/offentlig plats',
  'MEX_EASEMENT' = 'Servitut',
  'MEX_TREES_FORESTS' = 'Träd, skog',
  'MEX_ROAD_ASSOCIATION' = 'Vägförening/Samfällighetsförening',
  'MEX_RETURNED_TO_CONTACT_SUNDSVALL' = 'Ärende åter till Kontakt Sundsvall',
  'MEX_SMALL_BOAT_HARBOR_DOCK_PORT' = 'Småbåtshamn/Kaj/Hamn',
  'MEX_SELL_LAND_TO_THE_MUNICIPALITY_PRIVATE' = 'Köpa kommunal mark, privatperson',
  'MEX_SELL_LAND_TO_THE_MUNICIPALITY_BUSINESS' = 'Köpa kommunal mark, företag',
}

export const CaseLabels = {
  PT: PTCaseLabel,
  FT: FTCaseLabel,
  MEX: MEXCaseLabel,
  ALL: { ...PTCaseLabel, ...MEXCaseLabel, ...FTCaseLabel },
};
